### PR TITLE
add check for qemu crash.

### PR DESCRIPTION
**Pull request by Xiaohua-Shen**

### CODE REVIEW

**Comment by paulczar** [comment]
please provide more details as to the reason for this as well as linking to the PR for the corresponding ursula-monitoring repo.

**Comment by Xiaohua-Shen** [comment]
This is related to RTC 339876, a request raised by operation team. I will change the check plugin based on your suggestion.

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by masteinhauser** [comment]
retest

**Comment by masteinhauser** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by epwn** [comment]
retest

**Pull request merged**
