### PR TITLE
[WIP]Add block migration related jellyroll

### PR DESCRIPTION
**Pull request by Xiaohua-Shen**
to forbidden block-migration for roles not in whitelist.

### CODE REVIEW

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by jeffreyzhou** [comment]
retest

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by jeffreyzhou** [comment]
retest

**Comment by jeffreyzhou** [comment]
retest

**Pull request closed without merging**
