### PR TITLE
Fixes #1405 remove deprecated alerts

### LINKED ISSUE #1405: remove - name: kernel-options and - name: network interface traffic metrics check from common/monitoring.yml
remove from ursula-monitoring only when fully deprecated

### PR DESCRIPTION
**Pull request by nealbrown**
… alerts

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by j2sol** [comment]
I like that we're removing these from getting turned on in new installs. I don't recall, did we discuss having tasks to explicitly remove these if they exist on the filesystem, so that we take them out of existing installs?

**Comment by nealbrown** [comment]
Yes but that was out of scope for this card as I understood it

**Comment by nealbrown** [comment]
Should I add the tasks so we only make one pass?

**Comment by j2sol** [comment]
Nah, having a follow up PR is good enough. Out of scope sounds right.

**Comment by nealbrown** [comment]
test this please

**Comment by j2sol** [comment]
This will need to be rebased after #1506 is merged.

**Pull request closed without merging**
