### PR TITLE
increase mysql max_connections to 1k

### PR DESCRIPTION
**Pull request by zfeldstein**

### CODE REVIEW

**Comment by notnownikki** [comment]
Would it make sense to make this configurable? I'm just thinking that this affects file descriptor usage as well, so there might be deployments where we want a lower value.

**Comment by j2sol** [comment]
I'm on the fence. I don't think it hurts us much to have a higher water mark. Given it wasn't a tuneable before, I'm okay with just a bump of the hard set number.

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Pull request merged**
