### PR TITLE
Add more checks from inspec-openstack-security 

### PR DESCRIPTION
**Pull request by edtubillara**
This refactors the openstack checks to be set up in the inspec meta
role for glance, neutron, nova. It also adds additional checks for
aodh, ceilometer, and heat. More checks for glance was also added
and the list of glance configuration files has been added as well.

### CODE REVIEW

**Comment by edtubillara** [comment]
This depends on https://github.com/blueboxgroup/ursula/pull/2631 and will need to be rebased.

**Comment by nirajdp76** [comment]
ok to test

**Comment by edtubillara** [comment]
This PR depends on a one profile structure for ursula-inspec. It depends on this PR: https://github.com/blueboxgroup/ursula-inspec/pull/5.

This PR is also in conflict with a another PR and will need to be rebased with #2631

**Comment by paulczar** [comment]
split this out into two PRs.   one that adds the specs for heat etc back in,  the other for the ursula-inspec stuff.

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
