### PR TITLE
correct a typo when loading loadbalancer on horizon

### PR DESCRIPTION
**Pull request by panxia6679**

### CODE REVIEW

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Comment by epwn** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
