### PR TITLE
cluster check and metrics only execute once

### PR DESCRIPTION
**Pull request by Xiaohua-Shen**

### CODE REVIEW

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by Xiaohua-Shen** [comment]
related PR in blueboxgroup/ursula-monitoring is https://github.com/blueboxgroup/ursula-monitoring/pull/135, sorry for the mistake linkage.

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
