### PR TITLE
Add 'swift_backup_url' back to cinder.conf

### PR DESCRIPTION
**Pull request by blmartin**
Removed as part of a cleanup to use FQDNs in place of IPs. However,
cinder swift driver does not support certificates other than those
acknowledged by curl or python requests. Thus we must connect
directly to swift without ssl. If we gather the url's from keystone
we are then trying to connect to the swift ssl port without using
ssl.

### CODE REVIEW

**Comment by blmartin** [comment]
more changes to this PR incoming, please wait to merge

**Comment by nirajdp76** [comment]
:+1:

**Comment by blmartin** [comment]
The other issue with be handled with a separate PR. Feel free to comment and/or merge

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
Oh, please don't click the button that will update your branch. It puts a merge bubble in the PR and we don't want those. Please use `git rebase`  if you want to update your branch.

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
Passed CI locally. Merging.

**Comment by j2sol** [comment]
Closing in favor of #1422 which squashes the commits.

**Pull request closed without merging**
