### PR TITLE
allow cloud_admin to list domains

### PR DESCRIPTION
**Pull request by zfeldstein**

### CODE REVIEW

**Comment by j2sol** [comment]
I'm good with this, given that it's breaking horizon things, but I'd like @lihkin213 input on it.

Horizon appears to be making a domain list call when attempting to list projects.

**Comment by zfeldstein** [comment]
When logged in as cloud_admin viewing the projects panel in the identity dashboard does not work. The call attempts to list_domains and encounters a policy failure. This policy change will allow cloud_admin to view the projects panel. Stack trace when attempting to view projects panel is below:

[Thu May 19 22:04:42.740576 2016] [:error] [pid 4314:tid 139936257988352] Pure project admin doesn't have a domain token
[Thu May 19 22:04:42.740862 2016] [:error] [pid 4314:tid 139936257988352] Internal Server Error: /identity/
[Thu May 19 22:04:42.740888 2016] [:error] [pid 4314:tid 139936257988352] Traceback (most recent call last):
[Thu May 19 22:04:42.740891 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/openstack/current/horizon/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
[Thu May 19 22:04:42.740893 2016] [:error] [pid 4314:tid 139936257988352]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu May 19 22:04:42.740895 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../horizon/decorators.py", line 36, in dec
[Thu May 19 22:04:42.740897 2016] [:error] [pid 4314:tid 139936257988352]     return view_func(request, *args, **kwargs)
[Thu May 19 22:04:42.740901 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../horizon/decorators.py", line 52, in dec
[Thu May 19 22:04:42.740903 2016] [:error] [pid 4314:tid 139936257988352]     return view_func(request, *args, **kwargs)
[Thu May 19 22:04:42.740905 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../horizon/decorators.py", line 36, in dec
[Thu May 19 22:04:42.740907 2016] [:error] [pid 4314:tid 139936257988352]     return view_func(request, *args, **kwargs)
[Thu May 19 22:04:42.740909 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../horizon/decorators.py", line 84, in dec
[Thu May 19 22:04:42.740911 2016] [:error] [pid 4314:tid 139936257988352]     return view_func(request, *args, **kwargs)
[Thu May 19 22:04:42.740913 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/openstack/current/horizon/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
[Thu May 19 22:04:42.740915 2016] [:error] [pid 4314:tid 139936257988352]     return self.dispatch(request, *args, **kwargs)
[Thu May 19 22:04:42.740917 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/openstack/current/horizon/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
[Thu May 19 22:04:42.740919 2016] [:error] [pid 4314:tid 139936257988352]     return handler(request, *args, **kwargs)
[Thu May 19 22:04:42.740921 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../horizon/tables/views.py", line 159, in get
[Thu May 19 22:04:42.740923 2016] [:error] [pid 4314:tid 139936257988352]     handled = self.construct_tables()
[Thu May 19 22:04:42.740925 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../horizon/tables/views.py", line 150, in construct_tables
[Thu May 19 22:04:42.740934 2016] [:error] [pid 4314:tid 139936257988352]     handled = self.handle_table(table)
[Thu May 19 22:04:42.740937 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../horizon/tables/views.py", line 121, in handle_table
[Thu May 19 22:04:42.740939 2016] [:error] [pid 4314:tid 139936257988352]     data = self._get_data_dict()
[Thu May 19 22:04:42.740941 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../horizon/tables/views.py", line 187, in _get_data_dict
[Thu May 19 22:04:42.740943 2016] [:error] [pid 4314:tid 139936257988352]     self._data = {self.table_class._meta.name: self.get_data()}
[Thu May 19 22:04:42.740945 2016] [:error] [pid 4314:tid 139936257988352]   File "/opt/bbc/openstack-2016.1-mitaka/horizon/lib/python2.7/site-packages/openstack_dashboard/wsgi/../../openstack_dashboard/dashboards/identity/projects/views.py", line 117, in get_data
[Thu May 19 22:04:42.740948 2016] [:error] [pid 4314:tid 139936257988352]     t.domain_name = domain_lookup.get(t.domain_id)
[Thu May 19 22:04:42.740951 2016] [:error] [pid 4314:tid 139936257988352] AttributeError: 'NoneType' object has no attribute 'get'

**Comment by lihkin213** [comment]
Yes, Zack beat me to it. I was going to do that PR. :+1:

**Comment by j2sol** [comment]
Taking this in, but I wonder about project_admin too, since they need to be able to manage users as well.

**Comment by lihkin213** [comment]
Yes, project admin will need to list domains as well. I have @amwong looking at this. So she probably has a PR in the works.

**Pull request merged**
