### PR TITLE
Fix check-cinder-sessions

### PR DESCRIPTION
**Pull request by dlundquist**
Use nova API v1.1.

### CODE REVIEW

**Comment by j2sol** [comment]
Is there missing functionality in nova v2 api for this? 1.1 is deprecated and may get removed in future releases, we shouldn't be adding more usage of it in our infra.

**Comment by dlundquist** [comment]
@j2sol pythonnova client didn't include a v2 API, just v1_1 and v3, and v3 didn't work.

**Comment by j2sol** [comment]
Er... https://github.com/openstack/python-novaclient/tree/master/novaclient/v2  ?

**Comment by dlundquist** [comment]
https://github.com/openstack/python-novaclient/tree/2.15.0/novaclient/

**Comment by j2sol** [comment]
Well, okay, but it showed up as of 2.21.0. My point is that we now have another hardcoded usage of the 1.1 API, which is deprecated. It's one more thing we'll have to change when 1.1 goes away.

**Pull request merged**
