### PR TITLE
open port for vxlan on each node

### PR DESCRIPTION
**Pull request by panxia6679**
open port for vxlan on each node based on VM

### CODE REVIEW

**Comment by paulczar** [comment]
we should probably do an allow any:any inside the security group ?

**Comment by panxia6679** [comment]
IMHO, basically, allowing any:anyis easier, but it possibly hides some details.  I like to understand and open each port even if it needs some troubleshooting. :-)

**Comment by panxia6679** [comment]
I initially thought that we can open port by port. Later considering that there is no such restriction between bare metals , we can open any on vm. So drafts changes for your review.

**Comment by paulczar** [comment]
now that allows too much in!  I want to restrict what is allowed from 0/0 to just the necessary,  but anything inside the security group should be able to access anything else inside the security group.

**Comment by paulczar** [comment]
included as part of https://github.com/blueboxgroup/ursula/pull/2357

**Pull request closed without merging**
