### PR TITLE
add support for l3-router-check

### PR DESCRIPTION
**Pull request by twaldrop**

### CODE REVIEW

**Comment by j2sol** [comment]
Is this a duplicate of #1161 ?

**Comment by j2sol** [comment]
Due to the change we'll make in #1158 Please make sure that this check is on the RELEASE-1.3.x branch of ursula-monitoring.

**Comment by twaldrop** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
Might need to rebase this since #1182 merged.

**Comment by twaldrop** [comment]
rebased

**Pull request merged**
