### PR TITLE
feature: debug and verbose logging as variables

### PR DESCRIPTION
**Pull request by paulczar**
Allow setting variables to set debug and verbose logging options across the openstack services.

### CODE REVIEW

**Comment by masteinhauser** [comment]
@paulczar Can you rebase this against master after #670 has merged? Then we can finally take care of this.

**Comment by masteinhauser** [comment]
rebased this against master, running tests locally but expected to pass and will merge.

**Comment by j2sol** [comment]
needs rebase again. Wamp wamp.

**Comment by masteinhauser** [comment]
Yep, working on that still locally. Got distracted.

**Comment by masteinhauser** [comment]
Running a full build locally to confirm we don't have any other latent issues since we can't easily rebuild this PR via Jenkins.

**Comment by masteinhauser** [comment]
@j2sol Final rebase with successfully completed test run on local machine with verified debug logging configs. Cool stuff. Merging.

**Pull request merged**
