### PR TITLE
Added project and domain for new keystone authentication with mitaka

### PR DESCRIPTION
**Pull request by narengan**

### CODE REVIEW

**Comment by lihkin213** [comment]
LGTM

**Comment by j2sol** [comment]
Can you please rebase using your local git client, rather than the github UI, so that we can get rid of the merge commit in your PR?

**Comment by j2sol** [comment]
Other than getting rid of the merge commit, this looks fine.

**Comment by narengan** [comment]
Fixed rebase

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Pull request merged**
