### PR TITLE
WIP:Added rabbitmq inspec checks

### PR DESCRIPTION
**Pull request by narengan**

### CODE REVIEW

**Comment by nirajdp76** [comment]
retest

**Comment by edtubillara** [comment]
defaults-2.0.yml needs an entry for
inspec.controls.rabbitmq.profile_name
and
inspec.controls.rabbitmq.enabled

or else the rabbitmq inspec task in the rabbitmq role will fail.

Also the public repo for ursula-inspec will also need be added and inspec.controls.rabbitmq.enabled should be true by default.

**Comment by nirajdp76** [comment]
This PR needs to be closed, right?

**Comment by lihkin213** [comment]
yes, this PR should be closed

**Pull request closed without merging**
