### PR TITLE
[WIP] Add timeout for idle bash and SSH sessions

### PR DESCRIPTION
**Pull request by zrs233**

### CODE REVIEW

**Comment by j2sol** [comment]
My only concern with this are any long running Ansible actions we may do. I don't know if those would be considered "idle" or not. But we'll cross that bridge when we come to it.

**Comment by zrs233** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by craigtracey** [comment]
This should be feature flagged completely.

**Comment by zrs233** [comment]
Closing because we're moving this to flotsam

**Pull request closed without merging**
