### PR TITLE
Add nova-quota-sync script that rebuilds quotas.

### PR DESCRIPTION
**Pull request by ulyssesbbg**
From https://github.com/cernops/nova-quota-sync

Adding this script allows a standard way for support to rebuild damaged nova quotas without delving into the database.

### CODE REVIEW

**Comment by paulczar** [comment]
Can one of the admins verify this patch?

**Comment by paulczar** [comment]
ok to test

**Comment by dlundquist** [comment]
Tests failed:
```
TASK: [nova-control | install nova-quota-sync script] *************************
Thursday 02 July 2015  19:39:48 +0000 (0:00:01.947)       0:48:28.569 *********
failed: [173.247.105.25] => {"failed": true, "path": "/usr/local/sbin/nova-quota-sync", "state": "absent"}
msg: file (/usr/local/sbin/nova-quota-sync) is absent, cannot continue
failed: [173.247.105.35] => {"failed": true, "path": "/usr/local/sbin/nova-quota-sync", "state": "absent"}
msg: file (/usr/local/sbin/nova-quota-sync) is absent, cannot continue
```

We need to use the copy module rather than the file module here.

**Comment by ulyssesbbg** [comment]
Above patch now uses the copy module instead of the file module.  Can somebody please run the tests again?

**Comment by dlundquist** [comment]
Looks good to me, but I would like @craigtracey to weigh in too.

**Comment by j2sol** [comment]
This looks fine to me too.

**Comment by j2sol** [comment]
For the card, can this tool and usage be documented somewhere, and added to the release notes?

**Comment by dlundquist** [comment]
@ulyssesbbg Can you draft internal documentation for this tool, e.g. when and how to use.

**Comment by ulyssesbbg** [comment]
Added internal documentation: https://thevault.sea01.blueboxgrid.com/index.php/OpenStack_Quotas

**Pull request merged**
