### PR TITLE
Revert Paul's Change For LRO

### PR DESCRIPTION
**Pull request by ddaskal**
This will allow the sensu check to work on baremetals again.

### CODE REVIEW

**Comment by channus** [comment]
:+1:

**Comment by ddaskal** [comment]
I verified this on both baremetals and VM's so this should be safe to merge, especially after passing CI

**Comment by ddaskal** [comment]
Created new PR to master - https://github.com/blueboxgroup/ursula/pull/2443

**Comment by nirajdp76** [comment]
ported to master

**Pull request closed without merging**
