### PR TITLE
Update ownership and permissions for OpenStack conf files

### PR DESCRIPTION
**Pull request by edtubillara**
This updates the ownership and permissions for OpenStack
services conf files. This is to match the OpenStack security
guidelines.

### CODE REVIEW

**Comment by edtubillara** [comment]
I need to still figure out what to do about the missing glance files (schema.json and glance-manage.conf)

**Comment by narengan** [comment]
Yes we are planning to add the policy files to /etc/openstack-dashboard. Im working on it now. Horizon will break with Elvins PR because horizon cant read the policy.json files with 640 permissions.

**Comment by edtubillara** [comment]
Horizon will break if this is merged before @narengan's patch.

**Comment by narengan** [comment]
Can you add Heat to this as well?

**Comment by lihkin213** [comment]
ok to test

**Comment by nirajdp76** [comment]
ok to test

**Pull request merged**
