### PR TITLE
remove OS_DOMAIN_ID from heat tasks using stackrc

### PR DESCRIPTION
**Pull request by sinner-**
ursula runs are failing with the following error:

TASK [heat : remove heat domain user from default domain]
**********************
Wednesday 10 August 2016  02:14:53 +0000 (0:00:01.580)       0:46:44.776
******
fatal: [NODE.FQDN]: FAILED! => {"changed": true, "cmd":" ./root/stackrc; openstack --os-auth-url\"https://dummy-test.open-test.ibmcloud.com:5000/v3\" user delete --domain default heat_domain_admin", "delta": "0:00:00.593237","end": "2016-08-10 02:14:54.516346", "failed": true,"failed_when_result": true, "rc": 1, "start": "2016-08-10 02:14:53.923109", "stderr": "Authentication cannot be scoped to multiple targets. Pick one of: project, domain, trust or unscoped", "stdout": "", "stdout_lines": [], "warnings": []}

because the OS_DOMAIN_ID in the ansible task is conflicting with the contents of /root/stackrc

### CODE REVIEW

**Comment by lihkin213** [comment]
I am not sure if this will fix it. I was able to run the above command just fine.
My environment is as follows
```OS_USER_DOMAIN_NAME=Default
OS_PROJECT_NAME=admin
OS_IDENTITY_API_VERSION=3
OS_PASSWORD=*********
OS_AUTH_URL=https://dummy-test.open-test.ibmcloud.com:5000/v3
OS_USERNAME=admin
OS_TENANT_NAME=admin
OS_DOMAIN_ID=default
OS_CACERT=/opt/stack/ssl/openstack.crt
OS_NO_CACHE=True
OS_PROJECT_DOMAIN_NAME=Default```

**Comment by sinner-** [comment]
Hi Nikhil,

Have messaged you privately about dedicated cloud where it can be reproduced.

Thanks.

**Comment by teampoke** [comment]
I think this should be okay. Another question is why are we using openstack cli here instead of using the ansible modules.

**Comment by j2sol** [comment]
The ansible modules have a defect in that it can't handle trying to do cross domain actions. We had to resort to the command line tool until things are fixed upstream in the openstack modules and shade code.

**Comment by j2sol** [comment]
This needs more work, I'm going to use this and then add to it in a new PR

**Comment by j2sol** [comment]
(also this problem doesn't necessarily exist on master, because we pin openstack-client-config). This is a problem that was exposed in the 3.0.0 tag where that is not pinned, but in reality, we're kind of doing things wrong by using OS_DOMAIN_ID.

**Comment by j2sol** [comment]
Closing in favor of #2114

**Pull request closed without merging**
