### PR TITLE
Get oidc package from Blue Box mirror instead of git

### PR DESCRIPTION
**Pull request by edtubillara**
Change the url to use the Blue Box mirror instead of git.

### CODE REVIEW

**Comment by pwplusnick** [comment]
:+1: LGTM

**Comment by j2sol** [comment]
ok to test

**Comment by lihkin213** [comment]
hmmm. I thought we were already pulling from the mirror. But good catch

**Comment by j2sol** [comment]
I think we override the location in our internal configs.

**Comment by j2sol** [comment]
retest

**Comment by edtubillara** [comment]
Hmm, just thought of something... do we need to check the package hash?

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
@edtubillara It wouldn't hurt to validate the hash, or get it into an apt repo so that apt itself can validate the hash. I'll merge this though as an incremental improvement.

**Pull request merged**
