### PR TITLE
set virtlogd_var_run_t for nova instances folder.

### PR DESCRIPTION
**Pull request by nirajdp76**
PR fixes below AVC where nova-compute run's under libvirtd_t process context

audit.log.1:type=AVC msg=audit(1489418975.073:186): avc:  denied  { append } for  pid=3312 comm="virtlogd" name="console.log" dev="dm-0" ino=24510486 scontext=system_u:system_r:virtlogd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:nova_var_run_t:s0 tclass=file

### CODE REVIEW

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
@paulczar can you please review this PR. Needed custom policy as well. 
Unit test Covered for following Nova actions:
boot, stop, start. resume, suspend, snapshot, lock, unlock, Hard reboot, soft reboot, shelve and unshelve

**Comment by nirajdp76** [comment]
retest

**Comment by lihkin213** [comment]
retest

**Pull request merged**
