### PR TITLE
add ironic test

### PR DESCRIPTION
**Pull request by zfeldstein**
Basic test to verify ironic api and conductor services are running.

### CODE REVIEW

**Comment by nealbrown** [comment]
👍

**Comment by j2sol** [comment]
So this looks okay, but ironic itself is disabled in CI so these tests aren't ran. Are we ready to turn ironic on so that we get coverage?

**Comment by zfeldstein** [comment]
Ah yeah, that was a mistake, i meant to flip it enabled. I'll push up that change.

**Comment by zfeldstein** [comment]
This actually can't be merged until this PR gets in:

https://github.com/blueboxgroup/ursula/pull/2115

**Comment by j2sol** [comment]
rebase

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
retest

**Comment by devananda** [comment]
Merely testing that the services started is not the same as testing that they are configured correctly and working. This is a step in the right direction, but it looks like nova-compute is still going to use the libvirt driver, so it's not actually able to provide any bare metal instances.

**Comment by j2sol** [comment]
@devananda that's correct. First we want to get test coverage that we can actually run the ironic roles to completion, which we've been missing. That's the MVP here. Once we have that in place, we can expand upon the testing either in our CI runs, or in nightly deeper integration tests.

**Pull request merged**
