### PR TITLE
change default signal transport to heat instead of cfn

### PR DESCRIPTION
**Pull request by panxia6679**

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by panxia6679** [comment]
looks the failing check is nothing related to my change. Can we rerun the testing? Thanks.
--------------
Downloading/unpacking enum34 (from cryptography>=0.7->pyopenssl)
  Error <urlopen error timed out> while getting https://pypi-mirror.openstack.blueboxgrid.com/root/pypi/+f/984/3e97527f3126c/enum34-1.0.4.zip#md5=9843e97527f3126c851df7afeb0524b3 (from https://pypi-mirror.openstack.blueboxgrid.com/root/pypi/+simple/enum34)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1092, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1238, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 602, in unpack_http_url
    resp = _get_response_from_url(target_url, link)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 638, in _get_response_from_url
    resp = urlopen(target_url)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 176, in __call__
    response = self.get_opener(scheme=scheme).open(url)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 155, in https_open
    return self.do_open(self.specialized_conn_class, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

Storing complete log in /root/.pip/pip.log

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Pull request merged**
