### PR TITLE
Remove unneeded ruby1.9.1 install

### PR DESCRIPTION
**Pull request by pwplusnick**

### CODE REVIEW

**Comment by j2sol** [comment]
:+1:

**Comment by j2sol** [comment]
ok to test

**Comment by sandfish8** [comment]
just curious, what ruby is server spec going to be using ?

**Comment by pwplusnick** [comment]
@sandfish8: It will be using the embeded Sensu Ruby.

**Comment by sandfish8** [comment]
-1

I don't think we should be coupling the ruby dependencies here.
If sensu updates it's ruby it could impact the other ruby tools.
imo we should vendor ruby to avoid gem dep hell, similar to what sensu does with it's omnibus approach.
It might be more practical to just have a system ruby since right now it seems like serverspec is the only client

**Comment by j2sol** [comment]
Serverspec exists just for sensu, so it makes sense that they're coupled, at least to me.

**Comment by sandfish8** [comment]
hmm that's true.  ok, withdrawing my -1.

**Pull request merged**
