### PR TITLE
Allow reset of neutron vxlan devices

### PR DESCRIPTION
**Pull request by wangxian-ibm**
Allows user to reset neutron vxlan devices on compute or controller hosts as needed by including the following in all.yml:
```
neutron:
   vxlan_reset:
      enabled: True
```

### CODE REVIEW

**Comment by j2sol** [comment]
:-1: 

With ursula-cli we already have the ability to do ad-hoc actions on hosts. We could simply do an ursula call to run the command module to call the neutron-reset script. There is no need to add a task in the middle of a play like this.

Even if we wanted to codify it in a play, it should exist as a separate playbook, not buried in the neutron role.

**Comment by wangxian-ibm** [comment]
Thanks for the feedback.
I will confirm with Sangeetha and find out why this needs to be in Ursula.

**Comment by ssrikant20** [comment]
As mentioned by @j2sol this should not be a task in the main ursula run because it will get executed every time ursula is run. It should be a separate play book. If ursula-cli can be used to run adhoc commands against a set of hosts controllers and computes, then it could be documented as such in the documentation.

**Comment by ssrikant20** [comment]
The requirement from the ops was to run the script against all the controllers and computes when disabling arp_responder to recreate vxlan devices rather than logging into each controller and compute node.

**Comment by sandfish8** [comment]
👍 
I actually prefer the initial approach.  The vxlan_reset flag defaults to False so it will only happen when that  var is overridden.  I think the most practical way to override would be passing it in via --extra-vars, which is a convention that we have started using more and more often.

**Comment by j2sol** [comment]
SO I'm confused as to what the utility of this is. What is the expected scenario of events that would lead to resetting vxlan?

**Comment by wangxian-ibm** [comment]
This is when a customer opens a ticket and requests a change in their current `arp_responder` configuration, both from enabled to disabled and disabled to enabled. The reason for this is mostly for enabling or disabling the Allowed Address Pair extension. This doc here has the details. https://github.ibm.com/BlueBoxDocs/Operations-and-Deployment-Docs/blob/master/Operations/Disabling_arp_responder.md

**Comment by j2sol** [comment]
So is that document missing the manual step to reset vxlan interfaces?

**Comment by wangxian-ibm** [comment]
Step 4 in the doc, running `neutron-reset -d vxlan` node by node is currently manual. After this PR, we can change it to say run ursula with `vxlan_reset` flag set to `True`.

**Comment by j2sol** [comment]
ok to test

**Comment by ssrikant20** [comment]
How is this script run normally when there is a network issue and network devices need to be recreated?

**Comment by wangxian-ibm** [comment]
In that case, user just wants to run `neutron-reset` without any parameters.

**Comment by sandfish8** [comment]
so would the operator run with something like this ?
```
... --tags=neutron --extra-vars='{"neutron": {"vxlan_reset": {"enabled": false}}}"
```

**Comment by j2sol** [comment]
vxlan reset defaults to off, and this is the ONLY neutron-reset command that's in the neutron tags. There is no other automation for running a neutron-reset.

**Comment by j2sol** [comment]
Merging, please back port to RELEASE-3.0.x if you feel that this should go into a 3.0.1 release to address operational concerns.

**Comment by sandfish8** [comment]
@j2sol undersood

**Pull request merged**
