### PR TITLE
Change ubuntu mirror url

### PR DESCRIPTION
**Pull request by j2sol**
Testing a mirror change for Myles

Change-Id: I9cad6cbe3f2b3039e880371c98cf66e429f3e32f

### CODE REVIEW

**Comment by masteinhauser** [comment]
retest

**Comment by timrchavez** [comment]
retest

**Comment by nirajdp76** [comment]
:+1:

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Pull request merged**
