### PR TITLE
Fix multipod route check

### PR DESCRIPTION
**Pull request by wangxian-ibm**
File name for `/etc/sysconfig/network-scripts/route-<interface>` should not have `.cfg` extension

### CODE REVIEW

**Comment by paulczar** [comment]
ok to test

**Comment by epwn** [comment]
retest

**Comment by epwn** [comment]
ok to test

**Comment by epwn** [comment]
retest

**Comment by epwn** [comment]
retest

**Comment by epwn** [comment]
ok to test

**Pull request merged**
