### PR TITLE
Fix Swift's motd

### PR DESCRIPTION
**Pull request by epwn**
Changing the path of the motd file swift writes to

### CODE REVIEW

**Comment by j2sol** [comment]
Lets not merge this just yet. @craigtracey is likely changing the format of the ursula-release file to be structured, so this would have to change too.

**Comment by j2sol** [comment]
Actually, for this, lets just drop another file into `/etc/update-motd.d/` as this is just a warning to be printed out, and not actually part of the ursula release data.

**Comment by epwn** [comment]
:+1: I like that idea. I'll hold off till craig's PR gets in

**Comment by j2sol** [comment]
ok to test

**Pull request merged**
