### PR TITLE
Drop all the pinned requirements

### PR DESCRIPTION
**Pull request by j2sol**
Upper constraints will keep us safe.

Change-Id: I7913c9430f2c395126061c1edc5304e257e9367c

### CODE REVIEW

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by nealbrown** [comment]
👍

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Pull request merged**
