### PR TITLE
adjust role to use repos list for yum

### PR DESCRIPTION
**Pull request by zfeldstein**
In some cases, roles have more then one repo to add (i.e. rabbit, common). Calling the repos role should allow you to pass multiple repos in a list vs making multiple calls.

### CODE REVIEW

**Comment by nirajdp76** [comment]
@zfeldstein could you please add description to the PR stating problem it is addressing. Thanks

**Comment by zfeldstein** [comment]
As @paulczar mentioned, this would break existing calls to the repo role. If we decide to use the list I'll update this PR to make sure the existing repos being added conform to the list format. If we dont' want the list we can just close this PR.

**Comment by paulczar** [comment]
I'm cool to go ahead with list if you update the rest of the roles to suit.

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
@zfeldstein just checking where this PR stands? Do we plan to make the changes to rest of the roles?

**Comment by paulczar** [comment]
closing all PRs with no recent activity.

**Pull request closed without merging**
