### PR TITLE
Improve upgrades with packages

### PR DESCRIPTION
**Pull request by j2sol**
Need to gather the facts correctly
Work around Ansible bug of set_fact + run_once as first task
Need to handle services that may not be present
Use a better setup for validating nova ssh
Add code to upgrade ceilometer

### CODE REVIEW

**Comment by ryshah** [comment]
:+1:

**Comment by ryshah** [comment]
Following can be changed in swift role https://github.com/blueboxgroup/ursula/blob/b1862fe28dd0dc8994c4dbf0fc5a30fdb5840c21/roles/swift-ring/handlers/main.yml#L3 

I can create separate PR for that if you like...

**Comment by j2sol** [comment]
@ryshah sure A follow up PR would be lovely.

**Comment by j2sol** [comment]
although I'm not done here, so maybe I'll just incorporate it here.

**Comment by j2sol** [comment]
This is ready for re-review.

**Comment by zfeldstein** [comment]
👍

**Pull request merged**
