### PR TITLE
wip_kilo rebase #1

### PR DESCRIPTION
**Pull request by zrs233**
Rebasing wip_kilo with master as of 8/21 to pull in latest changes

### CODE REVIEW

**Comment by paulczar** [comment]
failed tests ... may need to install functools into each of the venvs manually,  we saw this with packages too due to a bad upstream dependency.

```
TASK: [keystone | sync keystone database] *************************************
Saturday 22 August 2015  17:59:46 +0000 (0:00:00.929)       0:52:41.249 *******
failed: [173.247.105.3] => {"changed": true, "cmd": ["keystone-manage", "db_sync"], "delta": "0:00:00.434807", "end": "2015-08-22 17:59:46.948250", "rc": 1, "start": "2015-08-22 17:59:46.513443", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/local/bin/keystone-manage", line 30, in <module>
    from keystone import cli
  File "/usr/local/lib/python2.7/dist-packages/keystone/cli.py", line 24, in <module>
    from keystone import backends
  File "/usr/local/lib/python2.7/dist-packages/keystone/backends.py", line 13, in <module>
    from keystone import assignment
  File "/usr/local/lib/python2.7/dist-packages/keystone/assignment/__init__.py", line 15, in <module>
    from keystone.assignment import controllers  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystone/assignment/controllers.py", line 26, in <module>
    from keystone.assignment import schema
  File "/usr/local/lib/python2.7/dist-packages/keystone/assignment/schema.py", line 13, in <module>
    from keystone.common.validation import parameter_types
  File "/usr/local/lib/python2.7/dist-packages/keystone/common/validation/__init__.py", line 16, in <module>
    from keystone.common.validation import validators
  File "/usr/local/lib/python2.7/dist-packages/keystone/common/validation/validators.py", line 14, in <module>
    import jsonschema
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/__init__.py", line 12, in <module>
    from jsonschema.exceptions import (
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/exceptions.py", line 6, in <module>
    from jsonschema import _utils
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/_utils.py", line 6, in <module>
    from jsonschema.compat import str_types, MutableMapping, urlsplit
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/compat.py", line 39, in <module>
    from functools32 import lru_cache
ImportError: No module named functools32

FATAL: all hosts have already failed -- aborting
```

**Comment by paulczar** [comment]
This looks like a fairly straight forward rebase ...  not seeing anything too crazy here.   

Given this is a WIP branch I'm okay to merge it and fix the functools32 problem later,    but I want @j2sol to check this over before I do since its such a large changeset.

**Comment by zrs233** [comment]
@paulczar You're thinking we'll need to add functools32 as a pip dependency in the keystone role?

**Comment by paulczar** [comment]
@zrs233 yessir.   and potentially other projects.  from memory in giftwrap packages we had to add it to pretty much all the projects.

**Pull request merged**
