### PR TITLE
simplify boolean writing

### PR DESCRIPTION
**Pull request by rongzhus**
refer to [PR 2675](https://github.com/blueboxgroup/ursula/pull/2675)
changes `xx.enabled|default('True')|bool` to `xx.enabled|default(True) or xx.enable|default(true)`
changes `xx.enabled|default('False')|bool` to `xx.enabled|default(False) or xx.enabled|default(false)`
changes `xx.enabled|bool` to `xx.enabled`

### CODE REVIEW

**Comment by nirajdp76** [comment]
We cannot be making such changes across all the files. Why are we changing |bool   this should work fine.

**Comment by rongzhus** [comment]
Ansible can auto recognize `True` `true` `False` and `false` as boolean type. 
In ursula, we use several forms such as `xx.enabled|default(True)|bool` `xx.enabled|default('False')|bool` and `xx.enabled|default("True")|bool`, alrouth they all works fine, it is not brief enough. I modified all the file with caution and after modification the code works fine.

**Comment by chengtcli** [comment]
@nirajdp76 , I also prefer to fix these `|bool` places, otherwise other developers may still following this format, then more and more `|bool` exist in Ursula.
For `bool` filter, ansible doc only mentions [one case ](http://docs.ansible.com/ansible/playbooks_filters.html).
```To cast values as certain types, such as when you input a string as "True" from a vars_prompt and the system doesn't know it is a boolean value```

Yea, this PR changes too many files. We may be able to break it into several PRs.

**Comment by nirajdp76** [comment]
We do not need this change as current check with |bool is still valid ansible. Please close this PR.

**Pull request closed without merging**
