### PR TITLE
testenv: enable IPv6 tenant networks

### PR DESCRIPTION
**Pull request by dlundquist**
Configure a dual stack tenant network in testenv. Update neutron_subnet
module to support IPv6 addressing options (changes accepted upstream).

### CODE REVIEW

**Comment by paulczar** [comment]
this may not have actually passed tests ... got run by the new jenkins server I'm to test via PR.

**Comment by j2sol** [comment]
It did fail, https://jenkins.blueboxgrid.com/job/ursula/2533/

**Comment by j2sol** [comment]
This all seems fine, I can't see anything glaringly wrong.

**Comment by dlundquist** [comment]
retest

**Comment by dlundquist** [comment]
retest

**Pull request merged**
