### PR TITLE
Create linux bridge network interface and route only on non-SL based …

### PR DESCRIPTION
**Pull request by ssrikant20**
…BB deployment

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by j2sol** [comment]
I think this is okay, but I'd like @dlundquist to confirm.

**Comment by j2sol** [comment]
So this made tests fail, around the neutron router. I suspect some logic issues.

**Comment by ssrikant20** [comment]
Where can I look for the failed test results?
Please let me know.

**Comment by ssrikant20** [comment]
Discussed with Dustin. Will need to add additional check to account for CI environment.

**Comment by dlundquist** [comment]
This should work in environments where controllers act as gateway for pNodes and Neutron networks and environments where these gateways are provided by a dedicated network device, but breaks the CI environment. We need to add an additional `|| environment_is_ci` condition so we render this file in CI.

**Comment by j2sol** [comment]
Obviated by pr #1402

**Pull request closed without merging**
