### PR TITLE
Enable heat provisioner scheme for Ursula PR tests

### PR DESCRIPTION
**Pull request by yangzhang-ibm**
### Problem resolved:
Currently Ursula PR tests are setup using the Ansible os_* module to provision nodes and other resources.  This approach to provisioning and deployment orchestration for test environments is too cumbersome and not a good fit for creating multiple test environments.

### Solution of this commit:
This commit is to add the Heat provisioning capability to the Ursula PR tests and move what we currently have off of Ansible os_* modules onto Heat. Heat is decent at resource provisioning and deployment orchestration and defining environments is much cleaner with the use of templates.

### CODE REVIEW

**Comment by notnownikki** [comment]
ok to test

**Comment by yangzhang-ibm** [comment]
I just added another commit to my fork: Create tmp folder to avoid failure of ssh_key output by ursula-cil when using heat provisioner.
https://github.com/yangzhang-ibm/ursula/commit/cddf9607c42d81e8ac70f635ae877ab4d8f0904b
Without that, the Jenkins PR test will fail, I think it is kind of ursula-cli bug, while the above commit can resolve it on ursula code side.

**Comment by timrchavez** [comment]
Try to make your PR's only one commit.  Don't include merge commits.

**Comment by yangzhang-ibm** [comment]
I will do more code changes for this feature, and wrap all changes into one commit and then come up with a PR again.

**Comment by yangzhang-ibm** [comment]
closing this PR, I will create a new one with more code changes.

**Pull request closed without merging**
