### PR TITLE
enable ec2token in keystone and add ca file into ec2authtoken secion in heat.conf

### PR DESCRIPTION
**Pull request by panxia6679**
https://scertc.austin.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/144251

### CODE REVIEW

**Comment by j2sol** [comment]
I was under the impression that we weren't going to support the ec2 APIs. I need to clarify with some people.

**Comment by panxia6679** [comment]
More exactly, it is for OS::Heat::SoftwareDeployment with signal_transport: CFN_SIGNAL.

They are introduced by using OS::Heat::SoftwareDeployment with default value of signal_transport property in some yaml. Singal_transport is to specify what kind of call when sending signal back to heat. The default value is CFN_SIGNAL. With the default value, heat engine will generate ec2 token and VM will use that ec2 token to call back heat for authentication; when heat-api-cfn receives ec2 token, it will call Keystone for authentication. That is the background of problems on comment 2 and comment 3.

Taking env/manager.yaml as example, the following snippet is to define do_manager_init with SoftwareDeployment type.  It doesn't specify signal_transport so it uses default value of signal_transport: CFN_SIGNAL.

  do_manager_init:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: manager_init
      server:
        get_resource: s
      input_values:
        target: /opt/deploy

**Comment by panxia6679** [comment]
The problem was identified during testing logmet (which uses OS::Heat::SoftwareDeployment) in BB environment. The change is to fix that problem.

**Comment by j2sol** [comment]
In Kilo we can specify what the default should be for `signal_transport` when one isn't provided. Is there a more appropriate signal we can use that doesn't involve dragging in ec2? Choices of `CFN_SIGNAL, TEMP_URL_SIGNAL, HEAT_SIGNAL`

This is undocumented, but added here: https://review.openstack.org/#/c/182906/3

**Comment by panxia6679** [comment]
Yep, we can change default value to HEAT_SIGNAL. 

You said that you won't want to involve dragging in ec2. Does it mean that BlueBox would like to retire heat-cfn-api server? If that is the true, there are multiple occurrences to use CFN as signal URL and we have to go through all of them to change them to use Heat. Would you confirm? Thanks.

**Comment by panxia6679** [comment]
HI Jesse,

Niraj just talked with me and confirmed that we won't support ec2 in future even if it cfn service is in BB environment now.
I will submit another change to change default value to HEAT_SIGNAL. In addition, I will go through all similar default values for other resource type and make corresponding changes. 
Thanks for your quick comments and info.

Perry

**Comment by j2sol** [comment]
Thanks @panxia6679 . I'll close this one.

**Pull request closed without merging**
