### PR TITLE
WIP Fix ansible-lint complaints

### PR DESCRIPTION
**Pull request by pwplusnick**
This will fix the ansible-lint complaints brought up in issue #615. I ran ansible-lint against the latest site.yml. I'm still working on a few things, but here it is so far.

### CODE REVIEW

**Comment by CullenTaylor** [comment]
:+1:

**Comment by dlundquist** [comment]
test this please

**Comment by pwplusnick** [comment]
I have a few more changes to make, so please don't test yet. :) No reason to clutter the CI queue.

**Comment by j2sol** [comment]
ok to test

**Pull request merged**
