### PR TITLE
RHOSP and Ubuntu compatible neutron-reset script

### PR DESCRIPTION
**Pull request by rcwong**
changed regex to account for the extra "@if" tag at the end of tap device names. 
Added regex for netns because red hat adds its ID when performing a ip netns list

### CODE REVIEW

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
ok to test

**Comment by wangxian-ibm** [comment]
LGTM

**Pull request merged**
