### PR TITLE
first pass at kilo support

### PR DESCRIPTION
**Pull request by paulczar**
mind-blown

### CODE REVIEW

**Comment by paulczar** [comment]
retest

**Comment by j2sol** [comment]
Hey that's not really anything more than what I had on my kilo branch :)

**Comment by paulczar** [comment]
retest

**Comment by paulczar** [comment]
retest

**Comment by paulczar** [comment]
I believe we need to make a kilo branch of our horizon fork to resolve this ?   @j2sol ?

**Comment by j2sol** [comment]
@paulczar Yeah it's possible, hard to tell without seeing why Horizon is not up and running. The fact that the deploy finished is good news. We should probably toss this up into a set of VMs that won't get destroyed right away so we can poke at the environment.

Kilo as a feature is not scheduled until later this year though.

**Comment by zrs233** [comment]
We can close this because of the more recent PR of wip_kilo

**Pull request closed without merging**
