### PR TITLE
rabbitmq cluster cluster_node configuration, each node should have a type, disc or ram

### PR DESCRIPTION
**Pull request by douyq**
When deploy with rabbitmq.cluster=true, the rabbitmq service start failed as following error:
=INFO REPORT==== 7-Mar-2016::03:16:24 ===
Error description:
   {could_not_start,rabbit,
       {{cluster_node_type_mandatory,
            "The 'cluster_nodes' configuration key must indicate the node type: either {[...], disc} or {[...], ram}"},
        {rabbit,start,[normal,[]]}}}

A node can be a disk node or a RAM node. In most cases you want all your nodes to be disk nodes; RAM nodes are a special case that can be used to improve the performance clusters with high queue, exchange, or binding churn. When in doubt, use disk nodes only. 
The official site: https://www.rabbitmq.com/clustering.html

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by j2sol** [comment]
retest

**Comment by sandfish8** [comment]
seeing a lot of extra stuff in here.  Can this be rebased against master instead of merging it ?

**Comment by j2sol** [comment]
I only see the one change, although there is the ugly merge commit, but the end result is only one change.

**Pull request merged**
