### PR TITLE
Add check for existence of logrotate files

### PR DESCRIPTION
**Pull request by bdrich**

### CODE REVIEW

**Comment by lihkin213** [comment]
LGTM.

**Comment by pwplusnick** [comment]
:+1:

**Comment by pwplusnick** [comment]
One nicety would be something like this: https://github.com/pwplusnick/ursula/blob/7c50c6487dd1f7f653184742dad6894501006d5f/roles/percona-server/templates/etc/serverspec/mysql_spec.rb#L31

That would prevent it from also complaining about missing content if the files doesn't exist.

**Comment by j2sol** [comment]
ok to test

**Pull request merged**
