### PR TITLE
Expose cinder api v3

### PR DESCRIPTION
**Pull request by twaldrop**
expose endpoints for cinder api v3, update default endpoint to v3.

### CODE REVIEW

**Comment by nirajdp76** [comment]
Seems like cinderv3 service endpoint will be always created even when cinder is not enabled. We should add enabled flag to defaults-2.0.yml (to be consistent) and work under separate PR to get rid of cinverv2.enabled and cinderv3.enabled and rely on cinder.enabled only.
https://github.com/blueboxgroup/ursula/blob/master/roles/openstack-setup/tasks/users.yml#L18

**Comment by twaldrop** [comment]
cinderv3 flag is now enabled by default in defaults-2.0.  Logic to eliminate the need for this flag will be added in a later PR.

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by twaldrop** [comment]
retest

**Comment by twaldrop** [comment]
retest

**Comment by twaldrop** [comment]
retest

**Pull request merged**
