### PR TITLE
updates to fix broken ci jobs

### PR DESCRIPTION
**Pull request by pgraziano**
These were tested from another repo to make sure they work in CI.  Fixes include updating package versions based on repo updates, updating the openstack client to fix live migrations, resequencing some package installs, and changing the `pyopenssl` version to fix an SSL issue.

### CODE REVIEW

**Comment by pgraziano** [comment]
retest

**Comment by twaldrop** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Comment by twaldrop** [comment]
retest

**Comment by twaldrop** [comment]
retest

**Comment by twaldrop** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Comment by pgraziano** [comment]
retest

**Pull request merged**
