### PR TITLE
Upgrade deployments to pip 8.0.2

### PR DESCRIPTION
**Pull request by epwn**
Now that https://github.com/pypa/pip/issues/3384 has been resolved we
can use the latest version.

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by epwn** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
Please rebase this on master.

**Comment by epwn** [comment]
rebased

**Comment by zfeldstein** [comment]
:+1:

**Comment by j2sol** [comment]
ok to test

**Comment by epwn** [comment]
good to merge?

**Pull request merged**
