### PR TITLE
Avoid passing glance DB credentials as arguments

### PR DESCRIPTION
**Pull request by dlundquist**
Write a separate MySQL options file with Glance database credentials and
use that instead.

### CODE REVIEW

**Comment by blueboxjesse** [comment]
Please review and merge asap.

**Comment by j2sol** [comment]
:+1:

**Comment by j2sol** [comment]
On phone, can't merge. GitHub won't let me.

**Comment by paulczar** [comment]
failling because of misnaming of mysql .cnf file.   pushed commit to fix.  will merge when passes.

**Comment by dlundquist** [comment]
@paulczar thank you.

**Comment by paulczar** [comment]
rekicked tests after merging cinder fix.

**Pull request merged**
