### PR TITLE
[WIP]enable/disable lbaas ui on horizon as per neutron.lbaas flag

### PR DESCRIPTION
**Pull request by panxia6679**
lbaas ui distro is kind different from community's. It will install all necessary files during rpm installation without additional step to create links. The PR is to enable/disable rpm as per the flag for distro.

### CODE REVIEW

**Comment by nirajdp76** [comment]
ok to test

**Comment by panxia6679** [comment]
please hold on and I will have more testing with different sequence combination of enabling lb.

**Comment by paulczar** [comment]
looking good!  but you should really use a feature branch in your fork rather than using `master`

**Comment by panxia6679** [comment]
thanks review from Niraj and Paul. Will raise a new PR from another fork branch.

**Comment by panxia6679** [comment]
created PR #2506 to replace this one.

**Pull request closed without merging**
