### PR TITLE
ansible 2.3 support

### PR DESCRIPTION
**Pull request by zfeldstein**
With ansible >2.2  the service module has become an action plugin and is no longer able to be overridden as a module.  This PR removes our custom service module and uses the action plugin which does not support the "must_exist" parameter. The sefcontext module is also comes with ansible 2.3 and we do not need to vendor our own.  The apache2_module was updated to check syntax before enabling individual modules. This causes problems because before the module is enabled the config is broken, after enabling the module the config test will pass. This PR ignores configtest and re-orders the modules so that mod_proxy, proxy_http, and proxy_uwsgi go before other modules.

### CODE REVIEW

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
Retest

**Comment by jeffreyzhou** [comment]
retest

**Comment by zfeldstein** [comment]
retest

**Comment by jeffreyzhou** [comment]
retest

**Comment by twaldrop** [comment]
closing out old PRs that are no longer needed.

**Pull request closed without merging**
