### PR TITLE
Make syslog techspec compliant

### PR DESCRIPTION
**Pull request by epwn**
This will make syslog techpec compliant

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by j2sol** [comment]
@masteinhauser Please to be reviewing.

**Comment by j2sol** [comment]
retest

**Comment by masteinhauser** [comment]
Hold on merging. Comments to add. Likely duplication of messages and non-standard file for Ubuntu.

**Comment by epwn** [comment]
Waiting to hear back from higher ups before making any changes

**Comment by epwn** [comment]
Techspec author came back and said we are already compliant without this change. Closing this pr

**Pull request closed without merging**
