### PR TITLE
Use defaults-2.0.yml

### PR DESCRIPTION
**Pull request by j2sol**
Use ENV and config to find the defaults file.

### CODE REVIEW

**Comment by j2sol** [comment]
This is not right, will be working on it.

**Comment by nirajdp76** [comment]
:+1:

**Comment by j2sol** [comment]
retest

**Comment by paulczar** [comment]
:-1: 

defaults in ursula should remain `defaults.yml`    folks wanting to do more than one defaults version for different versions of ursula should solve that outside of here by using the `ursula-cli` options or modifying `ansible.cfg` in their older forks/branches of ursula.

**Pull request merged**
