### PR TITLE
removed horizon customize boolean for keystone policy

### PR DESCRIPTION
**Pull request by amwong**
In order for the Identity panel to appear for project/cloud_admin users, the horizon `keystone_policy.json` file needs to exist to give the roles admin access. This does not allow project/cloud_admin admin access to the APIs, as they are still being restricted by the original Keystone policy file.

### CODE REVIEW

**Comment by j2sol** [comment]
So, the customization is what brings in our extra code to allow project_admin and cloud_admin to have elevated rights. I think it's improper to change policy without those, which is why its tied to the customization boolean. To fully test that RBAC works the way we say it works for our customers, we need to enable horizon customization in the environment.

Can you help me understand why this change is being suggested?

**Comment by amwong** [comment]
The `horizon.customize` boolean still exists, but had been set to `false` by default and so the custom keystone_policy.json file was not being created. That file needs to always be created, so only the conditional code surrounding its creation was removed. 

I had patched this change in manually, so the other lines enabled by `horizon.customize` were still inactive. It didn't appear to me that using keystone_policy was dependent on them.

**Comment by zfeldstein** [comment]
The thinking was that there may be a use case where you would not want to have a customized horizon. If that use case is still valid, perhaps we could just default the customize boolean to true?

**Comment by j2sol** [comment]
The customized horizon requires some extra bits in Keystone that are not public, and are not suited for the public Ursula. The default for public ursula does not rely on cloud admin having elevated rights.

Validation testing of Blue Box Cloud should be performing installs that mimic production Blue Box Clouds, not the public Ursula.

**Comment by nirajdp76** [comment]
Agree with above comment. Our production Blue Box Clouds defaults-2.0.yml sets horizon.customize to True.

**Comment by amwong** [comment]
Ah okay. If the default in production is True, then there is no issue here. Closing this PR. Thanks

**Pull request closed without merging**
