### PR TITLE
Pull in ceph pool facts to all --tags run.

### PR DESCRIPTION
**Pull request by nirajdp76**
nova-data monitoring and openstack-setup depends on facts that are set in ceph-osd role. This was breaking ursula run when using --tags monitoring or --tags openstack-setup. In future, we will separate out this ceph facts in it;s own role so is easy to pull in via role dependency.

### CODE REVIEW

**Comment by j2sol** [comment]
This isn't tested by CI, going to rerun anyway.

**Comment by j2sol** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by j2sol** [comment]
Merging as no changes here disrupt CI

**Pull request merged**
