### PR TITLE
Remove controller services, packages, and sensu checks

### PR DESCRIPTION
**Pull request by nealbrown**
Highly destructive playbook for converged controller to compute migration

Mysql and LVM steps left as manual due to extreme danger of data loss

### CODE REVIEW

**Comment by sandfish8** [comment]
@nealbrown  we should get /etc/serverspec cleaned up to.  There are some controller specific specs there.

**Comment by nealbrown** [comment]
Ty @sandfish8 will do

**Comment by nealbrown** [comment]
retest

**Comment by nealbrown** [comment]
retest

**Comment by sandfish8** [comment]
👍

**Pull request merged**
