### PR TITLE
remove ec2 support

### PR DESCRIPTION
**Pull request by twaldrop**
Remove support for ec2 api.

### CODE REVIEW

**Comment by angstwad** [comment]
Couple of comments that might be confusing now that you're removing these filters in the heat template file:
```
./roles/heat/templates/etc/heat/api-paste.ini:# relies exclusively on authenticating with ec2 signed requests
./roles/heat/templates/etc/heat/api-paste.ini:# relies exclusively on authenticating with ec2 signed requests
```

**Comment by angstwad** [comment]
And now there's only one change with the new merge thing, so uhh, LGTM.  👍

**Comment by j2sol** [comment]
hah, so it was just a left over default.

Uh, instead of using the github button to "refresh" the branch or whatever, could you just do the git rebase on your own, and force push up? I hate the merge bubble.

**Comment by twaldrop** [comment]
retest

**Pull request merged**
