### PR TITLE
Use upstream ansible modules for keystone setup

### PR DESCRIPTION
**Pull request by j2sol**
We get access to os_user, os_keystone_role, and os_user_role now so lets
use them. Also we need to set up the admin user to have admin role on
the default domain, which is a new keystonev3 thing.

### CODE REVIEW

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by nirajdp76** [comment]
+1

**Pull request merged**
