### PR TITLE
mysql serverspec

### PR DESCRIPTION
**Pull request by narengan**
- [x] /var/lib/mysql file check

- [x] add audit logging check

### CODE REVIEW

**Comment by lihkin213** [comment]
@narengan do we have the techspecs for these serverspec checks defined in yaml format? If so, can you put a reference to the spec each of the change is checking. 

Everything else looks good to me.

**Comment by narengan** [comment]
No we dont. We need to update the yaml files

**Comment by j2sol** [comment]
Please rebase on master for Ansible 2.1 fixes.

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
I'm going to merge this, but I think you still need the YAML file updated, and then a follow up PR to point to the YAML line # in the comments or whatever we've been using for that.

**Pull request merged**
