### PR TITLE
update cpu check

### PR DESCRIPTION
**Pull request by sinner-**
This patch changes the parameters for the sensu CPU check to be
variable controlled rather than hardcoded and increases the crit
level for the sensu CPU check from 90 to 99.

### CODE REVIEW

**Comment by ulyssesbbg** [comment]
Looks good to me.

**Comment by sandfish8** [comment]
:+1:

**Comment by ulyssesbbg** [comment]
ok to test

**Comment by j2sol** [comment]
ok to test

**Pull request merged**
