### PR TITLE
Add common inspec checks

### PR DESCRIPTION
**Pull request by edtubillara**

### CODE REVIEW

**Comment by lihkin213** [comment]
ok to test

**Comment by maohuang81** [comment]
Please do not merge until we have RHOSP GA release branch cut. We will verify it after GA.

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
