### PR TITLE
Fix Bug In RabbitMQ Cluster.yml

### PR DESCRIPTION
**Pull request by ddaskal**
@zrs233 and I found this syntax issue that broke deployment.

### CODE REVIEW

**Comment by ddaskal** [comment]
Let me know if this should be PR'd to Release-3.0.x as well.

**Comment by j2sol** [comment]
Did you wind up trying to deploy to an environment where clustering was enabled for rabbit? We don't do that in production. Not sure how this was blocking some deployment.

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by ddaskal** [comment]
Clustering was enabled in one of our test team's environments, I'll double check that they really want it enabled.

**Comment by ddaskal** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by masteinhauser** [comment]
retest

**Comment by ddaskal** [comment]
retest

**Comment by j2sol** [comment]
Please rebase on master.

**Comment by ddaskal** [comment]
retest

**Comment by ddaskal** [comment]
retest

**Pull request merged**
