### PR TITLE
Move Ruby into memcache monitoring role

### PR DESCRIPTION
**Pull request by dlundquist**

### CODE REVIEW

**Comment by paulczar** [comment]
we actually don't need ruby at all ... or at least we shoudln't.   memcached monitoring uses the sensu embedded ruby.

**Comment by dlundquist** [comment]
@paulczar Well, it didn't pass CI before I added it back to the Memcache monitoring role. It needed ruby-dev to build the memcache gem, with viva changes it might not be needed at all.

**Comment by paulczar** [comment]
this may not have actually passed tests ... got run by the new jenkins server I'm to test via PR.

**Comment by j2sol** [comment]
Re-made this one as #2198

**Pull request closed without merging**
