### PR TITLE
setup: configure NAT on Neutron router

### PR DESCRIPTION
**Pull request by dlundquist**
Update neutron_router_gateway from upstream

### CODE REVIEW

**Comment by j2sol** [comment]
This will need to be rebased on the kvm bump.

**Comment by j2sol** [comment]
but otherwise looks :+1:

**Comment by dlundquist** [comment]
@j2sol how does this conflict with KVM bump? A rebase will be required to merge with #959, but not anything KVM related.

**Comment by j2sol** [comment]
All tests will fail because qemu-kvm package is hardcoded, and the old version is no longer in the repo. So unless the test is ran with the new version in the config it will fail.

I'm not 100% sure what's what failed the test, because I broke the test on accident in Jenkins itself. A re-push here to trigger jenkins again might be necessary.

**Pull request merged**
