### PR TITLE
WIP: Add oslo heartbeat timeout

### PR DESCRIPTION
**Pull request by agireud**
This adds the heartbeat_timeout_threshold parameter to the configurations that have rabbit.  Rabbit options have also been moved into the oslo_messaging_rabbit section for Kilo.

### CODE REVIEW

**Comment by j2sol** [comment]
How was a threshold of 30 decided upon? Why the deviation from default? Should it be a role default we can tweak?

**Comment by agireud** [comment]
Meant to put WIP in the title, these decisions still haven't been made.  I chose 30 because of your suggestion here https://github.com/blueboxgroup/ursula/issues/1343.  I can change all these to be configured in each role as a default.

I believe the default setting is 0 which disables the heartbeat altogether.

**Comment by j2sol** [comment]
oh HAHA, didn't realize it was my suggestion. Nice :+1:

**Comment by j2sol** [comment]
Please rebase on master

**Comment by agireud** [comment]
Added the option as a role default for each.  
Dependencies are now being enforced in each role.

**Comment by j2sol** [comment]
retest

**Pull request merged**
