### PR TITLE
Provide option to enable DEBUG logging in Swift

### PR DESCRIPTION
**Pull request by ryshah**

### CODE REVIEW

**Comment by craigtracey** [comment]
As log_level is something an operator might want to adjust, could we be explicit about the fall-through case?

```
{% else %}
log_level = INFO
{% endif %}
```

**Comment by ryshah** [comment]
Sure - will make that change. Left out else case since INFO is default log level

**Comment by j2sol** [comment]
In this case, lets go ahead and be explicit about falling back to INFO.

**Comment by j2sol** [comment]
:+1: Good to merge when tests pass.

**Pull request merged**
