### PR TITLE
Fix deprecated location for default_store

### PR DESCRIPTION
**Pull request by agireud**
Putting default_store in the [DEFAULT] section has been deprecated since Juno.  We verified this was causing failures in starting the glance service.  Moved to the correct location.

### CODE REVIEW

**Comment by zrs233** [comment]
:+1:

**Comment by j2sol** [comment]
Looks good to me. I'll let @paulczar decide if he wants this on the WIP.

**Comment by msambol** [comment]
Looks good. Thanks for doing this.

**Comment by zrs233** [comment]
Wondering why we're showing 8 commits here instead of just the 1. We rebased didn't we?

**Comment by j2sol** [comment]
A rebase (non-interactive) just plays your changes on top of the branch you're rebasing on. If you want to reduce the commits you need to rebase interactively (-i) and squash/fixup some commits.

**Pull request closed without merging**
