### PR TITLE
wip: experimental CentOS support

### PR DESCRIPTION
**Pull request by paulczar**
demo: `ursula --vagrant envs/example/allinone-centos site.yml`

this is just enough to get nova, glance, keystone, neutron seemingly fuctioning
correctly on CentOS.

have disabled heat, lbaas, etc.  also disabling logging/monitoring/etc.

### CODE REVIEW

**Comment by paulczar** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Pull request closed without merging**
