### PR TITLE
Add network troubleshoot tools

### PR DESCRIPTION
**Pull request by wangxian-ibm**
Adding the following network tools to help developers troubleshoot:
- tcpdump
- traceroute
- net-tools: arp, hostname, ifconfig, ipmaddr, iptunnel, mii-tool, nameif, netstat, plipconfig, rarp, route, slattach
- bind-utils: dig, host, nslookup

### CODE REVIEW

**Comment by wangxian-ibm** [comment]
ok to test

**Comment by masteinhauser** [comment]
ok to test

**Comment by masteinhauser** [comment]
retest

**Comment by wangxian-ibm** [comment]
retest

**Pull request merged**
