### PR TITLE
set baud rate for main serial port

### PR DESCRIPTION
**Pull request by paulczar**
backport for https://github.com/blueboxgroup/ursula/pull/2311

### CODE REVIEW

**Comment by masteinhauser** [comment]
Duplicate of #2311

**Comment by nirajdp76** [comment]
@masteinhauser this PR was to merge to RELEASE-3.1.x.

**Comment by nirajdp76** [comment]
reopening this PR as it is for RELEASE-3.1.x

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
