### PR TITLE
Extended functionality of swift_disk to handle invalid fs types or mo…

### PR DESCRIPTION
**Pull request by aldevigi**
Functions to streamline swift disk management

### CODE REVIEW

**Comment by craigtracey** [comment]
Please provide additional details on this change. What is its purpose? Is it blocking other work? What are the new features of the library? etc?

At first glance, I am not sure I like the idea of changing an existing filesystem.  This seems like it could be very dangerous for something like swift.  In cases where critical data is at stake, I prefer to take the fail-and-verify approach.

**Comment by ryshah** [comment]
We ran in to couple of issues in ICOS with SL provisioned hardware. Sometimes drives on the provisioned hardware were formatted with different FS types. Sometimes they will have partitions, some times not. Partitions if present could be mounted or not. This was breaking the automation and so we had created similar library in Ruby for Chef. 

The changes are attempt to bring over some of the functionality in to Ansible. One of the things that we consistently ran in to provisioning Swift was need to manually delete partitions from all nodes (since swift_disk does nothing if there is partition) before starting deploy. In nutshell the changes add following logic to current disk format logic:

+    #Algorithm to cover all use cases for formatting a disk to XFS
+    #1) If FS Type is not XFS
+        #1.1) If device is mounted, unmount it
+        #1.2) Format disk and mount it (done)
+    #2) If FS Type is XFS
+        #2.1) If device is not mounted or on wrong mount point
+            #2.2.1) Unmount (if needed)
+            #2.2.2) Format disk and mount it (done

**Comment by craigtracey** [comment]
I really do not like the idea of an ansible library making these decisions, especially for an uncertain use case.  I would much rather see this in an internal cleanup playbook.  Misusing the options proposed could cause significant and permanent harm to the Swift data.

**Comment by j2sol** [comment]
I agree with @craigtracey , this is far too dangerous of a tool to have in Ursula. Ursula needs to assume that the target system is ready for use. If the system is not ready for use when Ursula runs, that's a failing of the provisioning tool set, and should be resolved there.

**Comment by blueboxjesse** [comment]
Code is necessary, but it should live in our pre-seed setup code.

**Comment by ryshah** [comment]
It makes sense to have this logic in setup code (infra?) so systems are ready pre-deploy. 
It could be used by multiple components - ceph has similar check/logic in there playbooks.

**Comment by craigtracey** [comment]
Closing in favor of a different bootstrap playbook mechanism

**Pull request closed without merging**
