### PR TITLE
Fix identity panel for project_admin

### PR DESCRIPTION
**Pull request by edtubillara**
We are enabling a custom keystone policy file for horizon because
the horizon keystone policy and keystone policy need to be slightly
different when supporting the project admin. The horizon keystone policy
file requires project admin to be part of the admin required rule.
The project_id was also being used in the policy where project scope
did not matter. This has been corrected.
This fixes a bug where horizon fails to load parts of horizon
if the user has the project_admin role.

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by amwong** [comment]
`identity:validate_token` and `identity:validate_token_head` were also previously unscoped and may need to be changed as well

**Comment by timrchavez** [comment]
retest

**Comment by timrchavez** [comment]
retest

**Comment by amwong** [comment]
Also this should be independent of the `policy_for_horizon` boolean. We will need the keystone_policy.json to exist regardless of customized horizon in order for the Identity panel to work.

**Comment by j2sol** [comment]
@amwong are you stating that this PR needs more work?

**Comment by edtubillara** [comment]
It looks like zfeldstein protected the policy_for_horizon variable here in this commit:
https://github.com/blueboxgroup/ursula/commit/9d12eee58b62e353a9345b57602032596b3a9957

It looks like he fixed the horizon panel for cloud_admin and put a feature flag for horizon customization. I think project_admin would fall under this. IMO if the customization feature flag needs to be removed, it should be in a different commit and we should ask zfeldstein if we should remove the horizon customization feature flag altogether.

**Comment by j2sol** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by j2sol** [comment]
I'm going to merge, we can adjust after.

**Pull request merged**
