### PR TITLE
Add log forwarding host info to test envs

### PR DESCRIPTION
**Pull request by timrchavez**
Allow a test to optionally add log forwarding location info to
/etc/hosts.

### CODE REVIEW

**Comment by j2sol** [comment]
So, I know the omit filter is used in task arguments, but I don't think I've ever seen it used in a template itself.  Have you tested to see what happens if that ENV var isn't defined?

**Comment by timrchavez** [comment]
@j2sol You're right, what I didn't work, but I updated based on your suggestion.

**Comment by timrchavez** [comment]
Generate the variables and write them to the extra vars script that gets passed to ursula: https://github.blueboxgrid.com/blue-box-cloud/sitecontroller/pull/512

**Comment by j2sol** [comment]
Awesome lets give this a try!

**Pull request merged**
