### PR TITLE
Update ansible library for neutron (#2293)

### PR DESCRIPTION
**Pull request by wangxian-ibm**
NOTE: Due to known defect in community with the os_router module in Ansible 2.1, which is also responsible for managing the router's gateway and interfaces, this PR will not include these modules. Until patch is merged, we will make a separate PR.

- Removing local copy of Ansible libraries (version 2.0)
- This allows openstack-setup to use 2.1 libraries which are the most up-to-date
- Update calls to these libraries inside the roles

### CODE REVIEW

**Comment by j2sol** [comment]
retest

**Comment by ddaskal** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by wangxian-ibm** [comment]
retest

**Comment by wangxian-ibm** [comment]
retest

**Comment by wangxian-ibm** [comment]
retest

**Comment by wangxian-ibm** [comment]
retest

**Comment by wangxian-ibm** [comment]
retest

**Comment by nealbrown** [comment]
retest

**Pull request merged**
