### PR TITLE
create ci-ceph-ubuntu env for nightly ci job

### PR DESCRIPTION
**Pull request by chengtcli**
With this patch, we can run through ursula with ceph enabled on Ubuntu.
Once deployment completed, we can create VM, volume and attach volume to VM.
But this doesn't mean we support Ubuntu now, there are more cases we need to take care of.

### CODE REVIEW

**Comment by nirajdp76** [comment]
ok to test

**Comment by epwn** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by chengtcli** [comment]
@Xiaohua-Shen , please help review too

**Comment by chengtcli** [comment]
retest

**Comment by nirajdp76** [comment]
Is ok to have this env but we do not need to run the nightly CI job for this. We already have nightly job that cover ceph and swfit together.

**Comment by chengtcli** [comment]
tested on tardis by using VMs
env dir: envs/example/ci-ceph-ubuntu and env/example/ci-full-ubuntu

we can run through ursula.
For ci-ceph-ubuntu env, after deployment, we can create VM and volume, attach volume to VM, write data into volume in VM.
For ci-full-ubuntu env, we disable cinder. After deployment we can create VM.

**Pull request merged**
