### PR TITLE
cinder override volgroup

### PR DESCRIPTION
**Pull request by sandfish8**
This is work that @paulczar and @derek-zaguroli and I worked on.
@paulczar  can you give it a + 1 ?

we'll need to port it into master also.

### CODE REVIEW

**Comment by dlundquist** [comment]
+1

**Comment by paulczar** [comment]
seems legit +1

**Comment by paulczar** [comment]
failed tests ... may need to run through it manually to see why.

```
TASK: [create instances] ******************************************************
Thursday 09 July 2015  16:01:51 +0000 (0:00:02.970)       0:00:41.806 *********
failed: [127.0.0.1] => (item=jenkins-Ursula_Test_PRs-113-controller-0) => {"failed": true, "item": "jenkins-Ursula_Test_PRs-113-controller-0"}
msg: Error in creating the server, please check logs
failed: [127.0.0.1] => (item=jenkins-Ursula_Test_PRs-113-controller-1) => {"failed": true, "item": "jenkins-Ursula_Test_PRs-113-controller-1"}
msg: Error in creating the server, please check logs
failed: [127.0.0.1] => (item=jenkins-Ursula_Test_PRs-113-compute-0) => {"failed": true, "item": "jenkins-Ursula_Test_PRs-113-compute-0"}
msg: Error in creating the server, please check logs

FATAL: all hosts have already failed -- aborting
```

**Comment by j2sol** [comment]
retest

**Comment by sandfish8** [comment]
woot!  thank you

**Pull request merged**
