### PR TITLE
Update the federation modules to use shade

### PR DESCRIPTION
**Pull request by edtubillara**
This refactors the ansible modules related to federation to use
shade. This removes keystone_group and keystone_role because they
are not needed. They are replaced with ansible modules that already
exist (The existing modules also utilize shade). The following files
are changed to utilize shade for authentication.
 -keystone_federation_mapping.py
 -library/keystone_federation_protocol.py
 -library/keystone_identity_provider.py
 -library/keystone_service_provider.py
 -roles/keystone-setup/tasks/federation.yml

### CODE REVIEW

**Comment by lihkin213** [comment]
test this please

**Comment by nirajdp76** [comment]
ok to test

**Comment by narengan** [comment]
LGTM

**Comment by lihkin213** [comment]
Let us make sure that these modules are reporting the right status back. Also with the module for mapping, we need to be careful in `ursula` to not update the mapping on each run. The user is allowed to change the mapping and we cannot clobber the user's mapping changes.

**Comment by edtubillara** [comment]
I have updated the PRs and made sure the modules report the correct changed status. I made the update module to not be able to update the mapping so that we don't clobber the user's mapping changes. We will have to delete the mapping and then create the mapping in order to update.

**Comment by lihkin213** [comment]
retest

**Comment by lihkin213** [comment]
For the mapping module, you can also have a force flag that will overwrite the mapping (delete and recreate) as a convienience feature.

**Comment by lihkin213** [comment]
LGTM

**Pull request merged**
