### PR TITLE
Add multi cidr support

### PR DESCRIPTION
**Pull request by pwplusnick**
This will add the ability to list multiple CIDRs. In order to make it pass we had to add Jesse's PR #1389. If it fails, try running it again after it gets merged, I need to change one line in it.

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by j2sol** [comment]
Sorry, conflicting now :(

**Comment by pwplusnick** [comment]
No worries. I fixed it!

**Comment by timrchavez** [comment]
:+1:

**Comment by j2sol** [comment]
:rocket:

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by masteinhauser** [comment]
@pwplusnick 

Critical error in output:
```
The following packages have unmet dependencies:
 libffi-dev : Depends: libffi6 (= 3.1~rc1+r3.0.13-12) but 3.1~rc1+r3.0.13-12ubuntu0.1 is to be installed
```

Which, to me, looks like it is a conflict in how version dependencies are being expressed within the `libffi-dev` package which defines: `3.1~rc1+r3.0.13-12)` but `apt` can only find: `3.1~rc1+r3.0.13-12ubuntu0.1`

Full error in Jenkins:
```
TASK: [common | python dependencies] ******************************************
Friday 20 November 2015  00:45:59 +0000 (0:00:37.968)       0:10:53.906 *******
failed: [173.247.105.29] => (item=python-pip,python-libxml2,python-lxml,python-greenlet,python-openssl,python2.7-dev,python-httplib2,python-software-properties,python-virtualenv,python-mysqldb,python-jinja2,cryptsetup,libffi-dev,libssl-dev,libxml2-dev,libxslt1-dev) => {"failed": true, "item": "python-pip,python-libxml2,python-lxml,python-greenlet,python-openssl,python2.7-dev,python-httplib2,python-software-properties,python-virtualenv,python-mysqldb,python-jinja2,cryptsetup,libffi-dev,libssl-dev,libxml2-dev,libxslt1-dev"}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libffi-dev : Depends: libffi6 (= 3.1~rc1+r3.0.13-12) but 3.1~rc1+r3.0.13-12ubuntu0.1 is to be installed

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'python-libxml2' 'python-lxml' 'python-greenlet' 'python2.7-dev' 'python-httplib2' 'python-software-properties' 'python-virtualenv' 'python-mysqldb' 'python-jinja2' 'libffi-dev' 'libssl-dev' 'libxml2-dev' 'libxslt1-dev'' failed: E: Unable to correct problems, you have held broken packages.

failed: [173.247.105.34] => (item=python-pip,python-libxml2,python-lxml,python-greenlet,python-openssl,python2.7-dev,python-httplib2,python-software-properties,python-virtualenv,python-mysqldb,python-jinja2,cryptsetup,libffi-dev,libssl-dev,libxml2-dev,libxslt1-dev) => {"failed": true, "item": "python-pip,python-libxml2,python-lxml,python-greenlet,python-openssl,python2.7-dev,python-httplib2,python-software-properties,python-virtualenv,python-mysqldb,python-jinja2,cryptsetup,libffi-dev,libssl-dev,libxml2-dev,libxslt1-dev"}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libffi-dev : Depends: libffi6 (= 3.1~rc1+r3.0.13-12) but 3.1~rc1+r3.0.13-12ubuntu0.1 is to be installed

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'python-libxml2' 'python-lxml' 'python-greenlet' 'python2.7-dev' 'python-httplib2' 'python-software-properties' 'python-virtualenv' 'python-mysqldb' 'python-jinja2' 'libffi-dev' 'libssl-dev' 'libxml2-dev' 'libxslt1-dev'' failed: E: Unable to correct problems, you have held broken packages.

failed: [173.247.105.19] => (item=python-pip,python-libxml2,python-lxml,python-greenlet,python-openssl,python2.7-dev,python-httplib2,python-software-properties,python-virtualenv,python-mysqldb,python-jinja2,cryptsetup,libffi-dev,libssl-dev,libxml2-dev,libxslt1-dev) => {"failed": true, "item": "python-pip,python-libxml2,python-lxml,python-greenlet,python-openssl,python2.7-dev,python-httplib2,python-software-properties,python-virtualenv,python-mysqldb,python-jinja2,cryptsetup,libffi-dev,libssl-dev,libxml2-dev,libxslt1-dev"}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libffi-dev : Depends: libffi6 (= 3.1~rc1+r3.0.13-12) but 3.1~rc1+r3.0.13-12ubuntu0.1 is to be installed

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'python-libxml2' 'python-lxml' 'python-greenlet' 'python2.7-dev' 'python-httplib2' 'python-software-properties' 'python-virtualenv' 'python-mysqldb' 'python-jinja2' 'libffi-dev' 'libssl-dev' 'libxml2-dev' 'libxslt1-dev'' failed: E: Unable to correct problems, you have held broken packages.


FATAL: all hosts have already failed -- aborting
```

**Comment by j2sol** [comment]
retest

**Pull request merged**
