### PR TITLE
WIP DO NOT MERGE use ansible 2.3

### PR DESCRIPTION
**Pull request by zfeldstein**
Testing CI run using ansible 2.3.0. Do not merge.

### CODE REVIEW

**Comment by zfeldstein** [comment]
add to whitelist

**Comment by zsais** [comment]
add to whitelist

**Comment by nirajdp76** [comment]
ok to test

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
ok to test

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
closing this in favor of this -> https://github.com/blueboxgroup/ursula/pull/2842

**Pull request closed without merging**
