### PR TITLE
Clean commented script

### PR DESCRIPTION
**Pull request by brianhu2006**
cleanup commented code in script
1.remove gen-cert
2.remove commented code which is deprecated
3.remove setup controller_ip

### CODE REVIEW

**Comment by nirajdp76** [comment]
Please add description to the PR and squash ur commits.

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
why do we have changes from other PR here? example roles/inspec/defaults/main.yml  and other files.

We need to be careful on how we make PR's.  Blocking merge until is cleaned up.

**Comment by brianhu2006** [comment]
replace by pr https://github.com/blueboxgroup/ursula/pull/2684

**Pull request closed without merging**
