### PR TITLE
Add the HTTPOnly attributes to the CSRF and Session cookies to prevent access to cookies from JavaScripts

### PR DESCRIPTION
**Pull request by lihkin213**
The addition of the HTTPOnly attribute makes the cookie inaccessible to client side scripts and thus prevents cookie access even if a XSS flaw exists on the site. This is a good security practice for cookies that contain sensitive information.

### CODE REVIEW

**Comment by j2sol** [comment]
Can you expand in the commit message why we want to do this?

**Comment by lihkin213** [comment]
retest

**Comment by lihkin213** [comment]
@j2sol - updated the commit message.

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Pull request merged**
