### PR TITLE
Testing fixes for centos branch

### PR DESCRIPTION
**Pull request by notnownikki**

### CODE REVIEW

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by masteinhauser** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
retest

**Comment by notnownikki** [comment]
The aim of this was to get the test running, kinda expected it to fail, but this should be merged anyway as it gets the job to a state where it can run.

**Pull request merged**
