### PR TITLE
Let cloud_admin do live migration

### PR DESCRIPTION
**Pull request by yiheqilin**
recommit PR for jenkins checkout error
the previous PR is here: https://github.com/blueboxgroup/ursula/pull/2815
@lihkin213 @Xiaohua-Shen @nirajdp76

### CODE REVIEW

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by jeffreyzhou** [comment]
retest

**Comment by jeffreyzhou** [comment]
retest

**Comment by nirajdp76** [comment]
next time for git checkout issues, all u need to do is close and re-open same PR.

**Pull request merged**
