### PR TITLE
Remove Unused heat-cfn Enable

### PR DESCRIPTION
**Pull request by ddaskal**

### CODE REVIEW

**Comment by j2sol** [comment]
This will have no impact on release or CI.

**Comment by ddaskal** [comment]
Yeah I just wanted to make the PR so y'all could decide whether you wanted to simplify ursula a touch or not. It can go in a future release no problem, I just had someone ask me about this the other day and it made me curious to see why it's here (no reason apparently).

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by nirajdp76** [comment]
what is the context behind this PR? Seems like heat software deployment still needed this.

**Comment by j2sol** [comment]
The variable itself isn't used anywhere.

**Comment by nirajdp76** [comment]
LGTM

**Comment by ddaskal** [comment]
Thanks y'all, I just updated the branch so it should pass the test and get merged soon.

**Comment by j2sol** [comment]
retest

**Pull request merged**
