### PR TITLE
Enable cache for metadata agent and Neutron server

### PR DESCRIPTION
**Pull request by panxia6679**
Enable cache for metadata agent and Neutron server.

### CODE REVIEW

**Comment by nirajdp76** [comment]
ok to test

**Comment by Xiaohua-Shen** [comment]
retest

**Comment by paulczar** [comment]
is this required functionality or an optimization ?

**Comment by panxia6679** [comment]
Ah, it is for optimization. I had some verification and it really improves performance.  

Your query brought me to add more explanation and raise another query:

1) these added properties are for newton. That is to say only newton will interpret them and take effect. Mitaka will ignore it as it won't read the whole section of [cache]. It applies for metadata agent and dhcp agent. 

2) looks we are going to have one ursula to support both of mitaka on ubuntu and newton on rhel. They have different configuration on openstack configurations besides OS. Shall we define different template and use "if statement" to pick up different template individually as per value of os? Thanks.

**Comment by nirajdp76** [comment]
Master will be newton for both ubuntu as well as centos/rhel so we should not have different templates.

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
