### PR TITLE
enable vxlan to work on rhel of VM

### PR DESCRIPTION
**Pull request by panxia6679**

### CODE REVIEW

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
LGTM

**Comment by panxia6679** [comment]
there is something wrong with ci. The failure is not related to the commit. :-)  Would you please retest it?

fatal: [controller-0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

**Comment by nirajdp76** [comment]
retest

**Comment by epwn** [comment]
retest

**Pull request merged**
