### PR TITLE
increase MaxAuthTries in sshd_config

### PR DESCRIPTION
**Pull request by pgraziano**
This is needed when using ssh-agent with multiple keys and the key you need is deeper in the list than MaxAuthTries will allow you to use.

### CODE REVIEW

**Comment by paulczar** [comment]
This should probably be a configurable value defaulting to whatever the linux defaults are.

We should also look at templating out the whole ssh config file at some point rather than lineinfile tasks, but that could be a separate work item.

**Comment by j2sol** [comment]
16 seems really high. In what scenario would you have 15 keys in the agent being used to connect to these hosts?

Also you'll need to rebase on master.

**Comment by sandfish8** [comment]
-1 until we get that # of tries turns into a var

**Comment by j2sol** [comment]
change #1500 replaces this one and has merged. closing this one.

**Pull request closed without merging**
