### PR TITLE
freeze eventlet for nova

### PR DESCRIPTION
**Pull request by paulczar**

### CODE REVIEW

**Comment by j2sol** [comment]
:+1:

**Comment by dlundquist** [comment]
More details on the the Nova / eventlet incompatibility would be good, but fine to merge as is once tests pass.

**Comment by j2sol** [comment]
https://bugs.launchpad.net/nova/+bug/1407685

**Comment by j2sol** [comment]
Tests are failing because the fix for /dev/tty stuff never got backported, so it's still trying to ring a bell :grimacing:

**Pull request merged**
