### PR TITLE
Using ansible_os_family instead of os

### PR DESCRIPTION
**Pull request by epwn**
First pass at using the ansible_os_family variable instead of the os flag

### CODE REVIEW

**Comment by twaldrop** [comment]
add to whitelist

**Comment by nirajdp76** [comment]
is this even valid values?
ansible_os_family == 'rhel'

**Comment by epwn** [comment]
@nirajdp76: No. I am working on replacing the rhel with Redhat and ubuntu with Debian in these logic statements

**Comment by scoop206** [comment]
@epwn I'm seeing changes that are already in `centos` branch.  Can you rebase this ?

**Comment by epwn** [comment]
For sure, im not sure what happened there.

**Comment by epwn** [comment]
retest

**Pull request closed without merging**
