### PR TITLE
update upstart for aodh-api and ceilometer-api.

### PR DESCRIPTION
**Pull request by nirajdp76**
Adjust upstart for aodh-api and ceilometer-api to pass --port which is a change needed for newton.
In addition, remove passing --config-dir to aodh-api.

### CODE REVIEW

**Comment by epwn** [comment]
ok to test

**Comment by epwn** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
