### PR TITLE
Make use of custom state paths for services

### PR DESCRIPTION
**Pull request by j2sol**
For the services that create potentially large amounts of data, move the
data to a standard data path, /opt/stack/data/<service>. In some
deployments we may have a different filesystem mounted to
/opt/stack/data.

### CODE REVIEW

**Comment by sandfish8** [comment]
:+1:

**Comment by j2sol** [comment]
retest

**Comment by paulczar** [comment]
`/opt/stack/data` should probably be provided by a variable as the default ?

**Comment by j2sol** [comment]
Thanks for the feedback @paulczar 

I've updated the default to be `/var/lib` but set up CI so that it will test `/opt/stack/data`. We'll want to make a change in ursula_env to set this.

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by nirajdp76** [comment]
:+1:

**Pull request merged**
