### PR TITLE
Switch to "round-robin" mode for nova and keystone in haproxy

### PR DESCRIPTION
**Pull request by nirajdp76**
Allowing round-robin mode for nova and keystone in haproxy to support higher number of concurrent VM deployments.

### CODE REVIEW

**Comment by j2sol** [comment]
Even though it'll be more work, I think it makes more sense to define the balance within the endpoint definition. That's where the name, clear_port, enc_port, perfer_primary_backend data comes from, it would make sense to add the balance data there as well.

**Comment by nirajdp76** [comment]
sounds goods... will make the suggested change.

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
