### PR TITLE
added vnc_keymap option to nova.conf

### PR DESCRIPTION
**Pull request by clwheel**

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by j2sol** [comment]
This looks good, but I want to wait until after we get `2.1.0` out the door.

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
I'm going to merge this to master. can you open a back port to RELEASE-2.1.x so that we can get this into the next point release, to catch up with what's been done in production?

**Comment by clwheel** [comment]
Backport to RELEASE-2.1.x: https://github.com/blueboxgroup/ursula/pull/1788

**Pull request merged**
