### PR TITLE
Update glance to fix traversal bug

### PR DESCRIPTION
**Pull request by j2sol**
https://bugs.launchpad.net/glance/+bug/1400966

### CODE REVIEW

**Comment by dlundquist** [comment]
Failed CI, local CI run failed, will need to be rebased once #721 is merged.

**Comment by masteinhauser** [comment]
#721 has been merged.

**Comment by j2sol** [comment]
Tests pass, please review again @masteinhauser @dlundquist

**Comment by dlundquist** [comment]
Not too much to review here, but tests pass and I've verified the ref is the new stable/juno branch.

**Pull request merged**
