### PR TITLE
fix ceph log file permission

### PR DESCRIPTION
**Pull request by chengtcli**
1. make ceph.log owned by ceph:ceph, otherwise ceph can't write log into it.
2. use logrotate config file which brought by ceph itself, and remove the one created by ursula
3. update ceph_spec

### CODE REVIEW

**Comment by nirajdp76** [comment]
@Xiaohua-Shen can you review this.

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Comment by chengtcli** [comment]
Tested on tardis by using VMs
env dir: envs/example/ci-eph-redhat
enabled serverpsec in all.yml

1. ursula finished without error
2. ceph can write log into ceph.log on ceph mon and osd nodes
3. run serverspec check on ceph_mon/ceph_osd/controller/compute by `cd /etc/serverspec; /opt/sensu/embedded/bin/rspec`
    no ceph error reported
4. call logrotate manually on ceph_mon by `/usr/sbin/logrotate -s /var/lib/logrotate/logrotate.status /etc/logrotate.conf`
    ceph.log is rotated correctly, and ceph is able to write log into new ceph.log
5. ceph-osd.0.log is owned by root:ceph on node osd1, ceph-osd.x.log is owned by ceph:ceph on other osd nodes. After logrotate, ceph-osd.x.log is owned by ceph:ceph on all osd nodes(include node osd1), and ceph can write log into new ceph-osd.x.log.

I think this PR is ready to merge

**Comment by nirajdp76** [comment]
adding @lihkin213 fir consultation.

@chengtcli There is servespecs definition file that defines the contract. Consult with Nikhil on serverspec changes. Also, we have to ensure with these changes were do not break checks for ubuntu.

**Comment by chengtcli** [comment]
@nirajdp76 , I leaved msg to Nikhil about this PR.
I think these changes will not break checks for ubuntu. As we haven't run through master branch on ubuntu, we can't test it for now. I will keep an key on it when we work on Ubuntu support.

**Pull request merged**
