### PR TITLE
adjust /etc/hosts for rhel/centos and ubuntu

### PR DESCRIPTION
**Pull request by nirajdp76**
Enhance /etc/hosts templates to create entries using hostname_fqdn and hostname_short along with taking difference of operatingsystem into account.

### CODE REVIEW

**Comment by epwn** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
ok to test

**Comment by epwn** [comment]
ok to test

**Comment by nirajdp76** [comment]
test this please

**Comment by epwn** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Pull request merged**
