### PR TITLE
Remove Neutron external network interface config

### PR DESCRIPTION
**Pull request by dlundquist**
In some legacy deployments without firewalls we used the controllers as
gateways for the Neutron external and internal pNodes networks. All new
deployments use external network infrastructure to provide the gateway
for these networks. Remove code to automatically generate an
interfaces(5) file for the brq* interface for the external Neutron
network. Existing deployments will be unaffected since this file is
already written, and in most cases defined host_vars network_interfaces.
This will prevent erroneously assigning a duplicate IP address to the
controllers as the external default gateway.

### CODE REVIEW

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
This is failing PRs. Do we need the bits that are being done here in our CI environment?

**Comment by dlundquist** [comment]
@j2sol Yes, looks like I removed setup from CI environment in ea9e192d. Code removed bd0086af appears cleaner than ea9e192d.

**Comment by j2sol** [comment]
We need to move the network config code into the setup playbook for CI so that CI still works.

**Comment by j2sol** [comment]
The network config code being removed here needs to be added into `playbooks/ci-full/tasks/pre-deploy.yml` and `playbooks/ci-allinone/tasks/pre-deploy.yml`  or some other place that is more central.

These playbooks are called toward the end of `test/setup` which we call to stand up an environment for CI.

**Comment by pwplusnick** [comment]
PR #1402 should replace this.

**Pull request closed without merging**
