### PR TITLE
Port Standardization for Glance, Nova, NoVNC, Cinder and Neutron

### PR DESCRIPTION
**Pull request by narengan**
Port Standardization for glance, nova, novnc, cinder and neutron. Customer facing port has been changed to standard openstack ports. Keystone, heat etc will be included in the next PR

### CODE REVIEW

**Comment by j2sol** [comment]
ok to test

**Comment by j2sol** [comment]
Since this is changing configuration, we need something in upgrade.yml to alter the endpoints. Otherwise if we run this on an existing cloud we'll get some problems. I haven't taken much look on this other than that, review is still needed.

**Comment by paulczar** [comment]
I would love to see the openstack project itself listening on 127.0.0.1 on the correct port and then have haproxy listen on the 10.x IP on the controller nodes.   We would have to solve the fact that we also need haproxy to serve across the external VIP as well for systems that don't have a external firewall/LB doing it for them.

we should probably make both the listen_ip and port a variable in each role so that they can be easier reconfigured if they ever need to be.

**Comment by paulczar** [comment]
ok to test

**Comment by zrs233** [comment]
Gonna move these commits to a new branch to unblock those trying to use the updated __wip_kilo__ branch

**Pull request closed without merging**
