### PR TITLE
Update to later matching versions of rspec and rspec-core 

### PR DESCRIPTION
**Pull request by ulyssesbbg**
fixes defect https://jazzop27.rtp.raleigh.ibm.com:9443/ccm/web/projects/BlueBox%20Cloud#action=com.ibm.team.workitem.viewWorkItem&id=212317

### CODE REVIEW

**Comment by masteinhauser** [comment]
Confirmed in production testing in dal09 this resolves the serverspec error encountered.

**Comment by ulyssesbbg** [comment]
As mentioned in the defect, this fixes this error:

If you look at https://control.openstack.blueboxgrid.com/sensu/#/events?q=serverspec , you get a ton of serverspec checks that fail to run.  For example, on cfs-prestg-dal ds0030.dal09, the error is "Check failed to run: A JSON text must at least contain two octets!".  Full output is:

command
sudo /etc/sensu/plugins/check-serverspec.rb -d /etc/serverspec -s warning
name
serverspec-check
output
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate rspec-3.4.0, because rspec-core-3.5.1 conflicts with rspec-core (~> 3.4.0) (Gem::LoadError) from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require' from /etc/serverspec/spec/spec_helper.rb:1:in `<top (required)>' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /etc/serverspec/spec/localhost/ceilometer_spec.rb:1:in `<top (required)>' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `load_spec_files' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:100:in `setup' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in `run' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke' from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.5.1/exe/rspec:4:in `<top (required)>' from /opt/sensu/embedded/bin/rspec:23:in `load' from /opt/sensu/embedded/bin/rspec:23:in `<main>' Check failed to run: A JSON text must at least contain two octets!, ["/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `initialize'", "/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `new'", "/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "/etc/sensu/plugins/check-serverspec.rb:94:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

Myles figured out the fix and I made a PR of it.  Here he writes:  

For host ds0030.dal09, I was able to upgrade to later **matching** versions of rspec and rspec-core, this is like what **ursula** needs to do also. This is a failure of ursula, not SiteController or the serverspec check itself.

http_proxy=http://proxy.dal09.bbg:3128 /opt/sensu/embedded/bin/gem install rspec rspec-core


root@ds0030:~# sudo /opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-serverspec.rb -d /etc/serverspec -s warning 
170 examples, 0 failures
CheckServerspec OK: 170 examples, 0 failures


blueboxadmin@ds0030:~$ sudo  /etc/sensu/plugins/check-serverspec.rb -d /etc/serverspec -s warning
170 examples, 0 failures
CheckServerspec OK: 170 examples, 0 failures

**Comment by j2sol** [comment]
Please don't link to or reference private issues in public commits or change request messages.

The code is fine, but can you re-word the commit and subject?

**Comment by j2sol** [comment]
Please rebase on master as well.

**Comment by ulyssesbbg** [comment]
Updated commit/comment wording.  Hopefully that's better, @j2sol ?

**Comment by j2sol** [comment]
Too late, I already merged it :D

**Pull request merged**
