### PR TITLE
fix ubuntu CI

### PR DESCRIPTION
**Pull request by zfeldstein**
Fixes ubuntu CI after centos -> master merge.

### CODE REVIEW

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
Retest

**Comment by zfeldstein** [comment]
retest

**Comment by zfeldstein** [comment]
retest

**Comment by nirajdp76** [comment]
LGTM

**Pull request merged**
