### PR TITLE
WIP: Unpin packages

### PR DESCRIPTION
**Pull request by timrchavez**
Just for review purposes at this point.  A couple changes need to land in blueboxgroup/ansible-modules-core before merging this won't break the universe.

### CODE REVIEW

**Comment by j2sol** [comment]
So I'm curious, if we actually need all of python-fooclient stuff any more. Shade has taken over most of the things, it would be for openstack modules that are not `os_` namespaced, or for any direct calls to the clients. Can you try dropping some of them or figuring out which ones we can drop from reqs?

**Comment by j2sol** [comment]
So, we do need python-novaclient for the time being, and the version getting pulled in doesn't work well with the `nova_keypair` module in our fork of ansible-modules. I'm going to look at fixing that one up, or replacing it.

**Comment by j2sol** [comment]
Once #1491 merges this can be rebased and will likely work. Might even be able to leave python-novaclient commented out.

**Comment by j2sol** [comment]
retest

**Comment by paulczar** [comment]
closing old PRs

**Pull request closed without merging**
