### PR TITLE
enable_external_interface set to False in defaults-2.0.yml

### PR DESCRIPTION
**Pull request by ssrikant20**

### CODE REVIEW

**Comment by paulczar** [comment]
ok to test

**Comment by j2sol** [comment]
retest

**Comment by j2sol** [comment]
I believe you'll need to do something to get the CI runs to work. You may have to add this setting as true in the config that CI builds up. Perhaps somewhere in https://github.com/blueboxgroup/ursula/blob/master/test/setup#L62

In fact, the role default should be False, which it is. So this PR should do two things:
- Remove the `enable_external_interface` entry all together from `defaults-2.0.yml`
- Add a line during CI build up to enable the external interface.

**Comment by ssrikant20** [comment]
@j2sol @paulczar 

We should probably update the all.yml during CI build up to set this variable to true.
In test/setup, 

cat >> ${ROOT}/envs/test/group_vars/all.yml <<eof
  neutron: 
       enable_external_interface: True
eof

This would override the default in neutron-common/defaults/main.yml

**Comment by j2sol** [comment]
@ssrikant20 Sounds good, please adjust your PR accordingly, and take out the entry in defaults-2.0.yml

**Pull request merged**
