### PR TITLE
Add playbooks for ci-ceph-redhat

### PR DESCRIPTION
**Pull request by ivy275**

### CODE REVIEW

**Comment by nirajdp76** [comment]
ok to test

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
URSULA_TES_PR CI keeps failing with below error

```
00:50:31 fatal: [controller-1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"allow_unauthenticated": false, "autoremove": false, "cache_valid_time": 3600, "deb": null, "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": null, "name": "python-pip", "only_upgrade": false, "package": ["python-pip"], "purge": false, "state": "present", "update_cache": true, "upgrade": null}}, "msg": "No package matching 'python-pip' is available"}
00:50:32 fatal: [controller-0]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"allow_unauthenticated": false, "autoremove": false, "cache_valid_time": 3600, "deb": null, "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": null, "name": "python-pip", "only_upgrade": false, "package": ["python-pip"], "purge": false, "state": "present", "update_cache": true, "upgrade": null}}, "msg": "No package matching 'python-pip' is available"}
00:50:32 fatal: [compute-0]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"allow_unauthenticated": false, "autoremove": false, "cache_valid_time": 3600, "deb": null, "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": null, "name": "python-pip", "only_upgrade": false, "package": ["python-pip"], "purge": false, "state": "present", "update_cache": true, "upgrade": null}}, "msg": "No package matching 'python-pip' is available"}
00:50:32 
```

**Comment by epwn** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
retest

**Comment by ivy275** [comment]
https://jenkins.ci.blueboxgrid.com/job/Ursula_Test_centos_PRs/446/ and https://jenkins.ci.blueboxgrid.com/job/Ursula_Test_PRs/868/ both are passed for checking.

**Pull request merged**
