### PR TITLE
Add restart_if_running state to service module

### PR DESCRIPTION
**Pull request by j2sol**
This replaces the restart_if_running module and accomplishes the same goal.
An upstream PR will follow soon to add this functionality to core Ansible.

This was tested manually, returns unchanged if the service isn't running, but
if it is running the service is restarted correctly.

### CODE REVIEW

**Comment by j2sol** [comment]
This is on top of #790 so merge that one first.

**Comment by masteinhauser** [comment]
I merged #790 first, not sure why this is complaining about needing a rebase now...

**Comment by j2sol** [comment]
This one had 790 in the commit history as well, so a rebase was necessary to get github's lovely merge bubble into the mix. Rebased.

**Comment by masteinhauser** [comment]
Waiting on jenkins result, but this lgtm.

**Comment by j2sol** [comment]
Jenkins passed, merging.

**Pull request merged**
