### PR TITLE
reference image by it's id for ci-full-centos.

### PR DESCRIPTION
**Pull request by nirajdp76**

### CODE REVIEW

**Comment by paulczar** [comment]
looks like the CI job isoverriding the image-id anyways `$ ursula --ursula-debug --provisioner=heat --heat-stack-name=jenkins-Ursula_Test_centos_PRs-103_stack --ursula-user=centos --heat-parameters image=c71af5ba-7992-41c9-82d3-ce24c905ed42`    maybe @notnownikki can update it to not try to set the image id ?

**Comment by paulczar** [comment]
also we should update the CI job to not generate the heat stack template since we overwrite it with the one in envs/example/* anyways

**Comment by nirajdp76** [comment]
retest

**Comment by nirajdp76** [comment]
Sure, will pass CentOS job enhancement inputs to  @notnownikki

**Comment by nirajdp76** [comment]
retest

**Comment by notnownikki** [comment]
Ok, not sure what needs to be done here now because I see the IMAGE_ID was updated. So are we getting rid of it so it uses the default? or keeping what it was updated to?

**Comment by nirajdp76** [comment]
closing this as heat template is being reworked under PR https://github.com/blueboxgroup/ursula/pull/2369 to allow support for concurrent CI runs.

**Pull request closed without merging**
